services:
  db:
    image: postgres:15-alpine
    container_name: devtracker_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass123
      POSTGRES_DB: devtracker_db
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: